export * from './dominio.ts';
export * from './pncp-tabelas.ts';
export * from './texto.ts';
export * from './prazos.ts';
export * from './perfil.ts';
export * from './triagem.ts';
export * from './pncp-tipos.ts';
export * from './pncp-cliente.ts';
export * from './pncp-normalizar.ts';
